### ISSUE TITLE
Total charge incorrect

### ISSUE THREAD

**Issue by jthorton** [choderalab/espaloma#121]
Hi, I have been testing out espaloma using the master branch and the newest set of model parameters and have found that the total molecular charge predicted by the network always seems to be neutral even with charged molecules, attached is a simple example using ammonium. I am unsure if there is an easier way to inspect charges rather than an openmm system?

```python
from openff.toolkit.topology import Molecule
import torch
import espaloma as esp
import numpy as np

mol = Molecule.from_smiles("[NH4+]")
esp_model = torch.load("espaloma-0.2.2.pt")
mol_graph = esp.Graph(molecule)
esp_model(mol_graph.heterograph)

system = esp.graphs.deploy.openmm_system_from_graph(mol_graph, charge_method="nn")
# this seems to be the nonbonded force
force = system.getForce(1)
charges = []
for i in range(force.getNumParticles()):
    charge, _, _ = force.getParticleParameters(i)
    charges.append(charge) 
np.sum(charges)
```
> Quantity(value=0.0, unit=elementary charge)

**Comment by yuanqing-wang** [comment]
Thanks for proposing the fix and so sorry for the delay since I had been on vacation. Supposedly the charge should be fed into the network here: https://github.com/choderalab/espaloma/blob/8081037ba937abf1c9999d866e5bd4e4eca278ce/espaloma/nn/readout/charge_equilibrium.py#L65 

This must somehow have not been called in the 0.2.2 model. Let me look into this.
